### ISSUE TITLE
do u have any lead on this problem

### ISSUE THREAD

**Issue by Daveads** [Kerumen/react-native-awesome-card-io#106]
![screenshot 23](https://user-images.githubusercontent.com/32952682/45012225-05509d00-b00e-11e8-9182-1e9f73a0fad8.png)
`have this problem been fixed by react-native`

**Comment by yvasiuk-sphere** [comment]
weird issue: poor text description, picture seems to be irrelevant

@Daveads please, fix it or close forever

**Comment by Kerumen** [comment]
As @yvasiuk-sphere said, lack of description and no relevant errors.

I close this one, feel free to open a new issue with a more detailed explanation.
