### ISSUE TITLE
Getting only the image of the scanned card, instead of the credit card object.

### ISSUE THREAD

**Issue by manik-mahajan** [Kerumen/react-native-awesome-card-io#107]
**Issue:** I'm expecting the credit card object as the return value of didScanCard but I'm only getting the card image.

**Code Snippet:**
        <CardIOView
          languageOrLocale="en_AU"
          guideColor="#FF0000"
          useCardIOLogo
          hideCardIOLogo={false}
          allowFreelyRotatingCardGuide
          scanInstructions="Hold card here. It will scan automatically."
          scanExpiry
          scannedImageDuration={2}
          detectionMode={CardIOUtilities.DETECTION_MODE.IMAGE_AND_NUMBER}
          **didScanCard={(card) => {
            console.log('card: ', card);
          }}**
          style={{ flex: 1 }}
        />

**Output of console.log:**
card:  iVBORw0KGgoAAAANSUhEUgAAAawAAAEOCAIAAABafrQeAAAAAXNSR0IArs4c6QAA
ABxpRE9UAAAAAgAAAAAAAACHAAAAKAAAAIcAAACHAAEs7Uapnu4AAEAASURBVHgB
jL0Hd1fH0ubLB5j7zp2ZYxuTTQYRJSGUc06IJAQSUSCQyMHknIPBNtkGY5OjECBA
QiTb5z1vmLmz7le6v6pn79YGn1nrssrt3tXVtTtUPbu6e++/BuzaunXPju2H9u09
evjI4YOHDuzbf+zQwePHjhw9cmjPrt3rOtYuXry4oaGhoqKipKg4PzcvOzMra2Ym
/7KzM3OyM3NzsvJycmFmZ83MycnJz8/Pzc3NysrKzc4pyOMij1L+KyjIK8jPzc/L
KcrLLc7PKynIJxUnLzc7PzsLyssybeg0VWjMzMjOmAGTy5kZ6VDWjPTM9LSM1Okz......

**Comment by Kerumen** [comment]
Can you try with the [last version](https://www.npmjs.com/package/react-native-awesome-card-io/v/0.9.0) of the library?
If it doesn't fix the problem, feel free to reopen the issue with a reproduction, I'll investigate!
