### ISSUE TITLE
Missing `v0.8.0` tag -> CocoaPods fail

### ISSUE THREAD

**Issue by danielgindi** [Kerumen/react-native-awesome-card-io#111]

**Comment by Kerumen** [comment]
Sorry I forgot to push! Should be good now :)

**Comment by thierryskoda** [comment]
Not sure if this is a related issue but I'm still receiving `No podspec found for `RNAwesomeCardIO` in `../node_modules/react-native-awesome-card-io`  with version 8.0.0
