### ISSUE TITLE
Issue with the android build

### ISSUE THREAD

**Issue by navneetccna** [Kerumen/react-native-awesome-card-io#112]
Gradle issue

com.android.tools.build:gradle:3.2.1
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
compileSdkVersion 26
buildToolsVersion '28.0.3'
"react-native-awesome-card-io": "^0.8.0",

Gradle sync failed: Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.3.1).
Searched in the following locations:
https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar

**Comment by peterholcomb** [comment]
I had to roll back to 0.7.0 temporarliy.  That got me past this issue.

**Comment by akashsharma88** [comment]
I don't know but when i include `google()` in the `node_modules\react-native-awesome-card-io\android\build.gradle` file  in repositories of buildscript and allprojects block,
It works for me

`buildscript {
    repositories {
        google() // added this line 
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        google() // added this line
        jcenter()
        maven { url "$projectDir/../node_modules/react-native/android" }
    }
}`
