### ISSUE TITLE
React/RCTAnimationType.h file not found

### ISSUE THREAD

**Issue by almsx** [Kerumen/react-native-awesome-card-io#114]
Hi.

I followed the installation instructions in React Native. My application has had a detach process to use this functionality to have previously been written in Expo / XDE. I have only had the error under iOS since Android has worked wonders.

The project is already integrated into the .xcworkspace file and sends the following error:

React / RCTAnimationType.h file not found

I appreciate the support for this issue.

Regards,
Alberto

**Comment by slorber** [comment]
hey, by chance did you find any solution? I have a similar issue here also on expo ejected project: https://github.com/Kerumen/react-native-awesome-card-io/issues/116

**Comment by slorber** [comment]
@almsx I may have found a solution that could work for you too: https://github.com/Kerumen/react-native-awesome-card-io/issues/116#issuecomment-446982188

**Comment by Kerumen** [comment]
Version [v0.9.0](https://www.npmjs.com/package/react-native-awesome-card-io/v/0.9.0) is now released with Pod support!
