### ISSUE TITLE
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.reject(java.lang.String, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by avnish-chuchra** [Kerumen/react-native-awesome-card-io#115]
@Override
public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
  if (requestCode != CARD_IO_SCAN) {
    return;
  }
  if (data != null && data.hasExtra(CardIOActivity.EXTRA_SCAN_RESULT)) {
    CreditCard scanResult = data.getParcelableExtra(CardIOActivity.EXTRA_SCAN_RESULT);
    WritableMap res = Arguments.createMap();
    res.putString("cardType", scanResult.getCardType().getDisplayName(data.getStringExtra(CardIOActivity.EXTRA_LANGUAGE_OR_LOCALE)));
    res.putString("cardNumber", scanResult.cardNumber);
    res.putString("redactedCardNumber", scanResult.getRedactedCardNumber());
    res.putInt("expiryMonth", scanResult.expiryMonth);
    res.putInt("expiryYear", scanResult.expiryYear);
    res.putString("cvv", scanResult.cvv);
    res.putString("postalCode", scanResult.postalCode);
    res.putString("cardholderName", scanResult.cardholderName);
    promise.resolve(res);
  } else {
    promise.reject("user_cancelled", "The user cancelled");
  }
}

can you add following condition in above method 
 if (promise == null) {
          return;
 } with following condition 
 if (requestCode != CARD_IO_SCAN) {
    return;
  }

**Comment by ObidosDev** [comment]
I am pretty sure there is problem. Let's make it more not obvious. Because any developer may set action code to 1
`public static final int CARD_IO_SCAN = 1;`
Also (promise == null) mean that scanCard was not called. Just some other activity with result code 1 was called

**Comment by Kerumen** [comment]
Fixed by https://github.com/Kerumen/react-native-awesome-card-io/pull/141
