### ISSUE TITLE
RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by slorber** [Kerumen/react-native-awesome-card-io#116]
Hi,

I have a freshly ejected Expo SDK31 app and not able to run because of this error.

![image](https://user-images.githubusercontent.com/749374/49930569-2bb38d80-fec5-11e8-890e-60b511f4570e.png)

I'm not an iOS developer so I don't totally understand the issue here.

The ejected Expo ios project is using cocoapods so I run `pod install` on it. It actually didn't install anything from card.io which is expected because this pr is not merged: https://github.com/Kerumen/react-native-awesome-card-io/pull/77/files

Do you have any practical experience integrating this library inside a RN project that uses cocoapods? Have you tested installation on an Expo ejected project? That would be very helpful because many of us install this kind of library on an Expo ejected project

**Comment by slorber** [comment]
I tried to set the absolute path (recursive) as header search path and I still get the same error:

`/Users/sebastienlorber/Desktop/projects/shotgun/b2c-rn/node_modules/react-native/React`


cc @peacechen as you seem to know more about header search path as me

**Comment by slorber** [comment]
That [answer](https://stackoverflow.com/a/43340802/82609) seems related, unfortunately I can't really apply it because I don't have React.xcodeproj anywhere. I guess this is because React is in my podfile. Any idea how to ask XCode to build React from pods first, and only then card.io library?

**Comment by slorber** [comment]
I tried many things without great success.

The solution that worked for me was to create my own local podspec for this project, which actually declare React as a dependency to ensure it's built before this lib.

```
Pod::Spec.new do |s|

  s.name           = "RNCardIO"
  s.version        = '0.8.1'
  s.license        = { :type => 'MIT' }
  s.homepage       = 'https://github.com/Kerumen/react-native-awesome-card-io'
  s.summary        = 'CardIO for ReactNative'
  s.authors        = 'Sébastien Lorber'


  s.platform       = :ios, "8.0"
  s.source         = { :git => 'git@github.com:Kerumen/react-native-awesome-card-io.git', :tag => "v#{s.version}" }
  s.source_files   = 'ios/*.{h,m}'

  s.dependency 'React'
  s.dependency 'CardIO', '5.4.1'

end
```


```

  pod 'RNCardIO',
    :podspec => "./RNCardIO.podspec",
    :inhibit_warnings => true
```

**Comment by peacechen** [comment]
@slorber 
Great that you found a solution for this.  I was not using CardIO as a pod, but that sounds like a better way to fetch the dependency.

**Comment by Kerumen** [comment]
Version v0.9.0 is now released with Pod support!
