### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by peterchibunna** [Kerumen/react-native-awesome-card-io#119]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/react-native-awesome-card-io) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by Kerumen** [comment]
I removed the CardIO dependency in v0.9.0. Can you try this version and see if it solves your issue? Thanks!
