### ISSUE TITLE
IOS Issues with Scanning

### ISSUE THREAD

**Issue by Priyatham51** [Kerumen/react-native-awesome-card-io#123]
I tried to run the example project to scan a credit card. The success completion handler is never getting executed.  This is happening only when I try to scan the card. **Enter Manually** option is working without any issues. 

![img_0001](https://user-images.githubusercontent.com/1404457/54015775-91668d00-4135-11e9-8fae-1a09a63722ae.jpg)

Anyone else having the same issues?

Note: Haven't tried this in Android.

**Comment by Priyatham51** [comment]
@Kerumen  can you please take look into this 🙏

**Comment by Priyatham51** [comment]
@Kerumen  I was able to figure this out with trial and error process. 
I had to add the following lines to get this working 

`componentWillMount() {
        if (Platform.OS === 'ios') {
          CardIOUtilities.preload();
          **CardIOUtilities.detectionMode = 'AUTOMATIC'**
        }
    }
`

and 
`
**var config = {suppressScannedCardImage: true, hideCardIOLogo:true, requireCardholderName:true, requirePostalCode:true}**
        CardIOModule
        .scanCard(config)
        .then(card => {
          // the scanned card
          console.log(card);
        })
        .catch(() => {
          // the user cancelled
        })
`

**Comment by Priyatham51** [comment]
`dasf`

**Comment by Priyatham51** [comment]
Can we make sure that`CardIOUtilities.detectionMode = 'AUTOMATIC'` is set by default ?

**Comment by luckycharm313** [comment]
I had same issue like @Priyatham51. I can't detect card info in both iphone and android.
Any solutions?

**Comment by ss910423** [comment]
I can't scan as well. Anyone can let me know the way to scan? Thank you

**Comment by Kerumen** [comment]
Can you try with the [last version](https://www.npmjs.com/package/react-native-awesome-card-io/v/0.9.0) of the library?
If it doesn't fix the problem, feel free to reopen the issue with a reproduction, I'll investigate!
