### ISSUE TITLE
App crashes / Can't run

### ISSUE THREAD

**Issue by brunolemos** [Kerumen/react-native-awesome-card-io#13]
I'm trying the basic `CardIOView` example from the readme, but it's not working.
The xcode aborts with an exception when I get to open the page that has the cardio component.

```
libsystem_kernel.dylib`__abort_with_payload:
    0x18e390d6c <+0>:  movz   x16, #0x209
    0x18e390d70 <+4>:  svc    #0x80
->  0x18e390d74 <+8>:  b.lo   0x18e390d8c               ; <+32>
    0x18e390d78 <+12>: stp    x29, x30, [sp, #-16]!
    0x18e390d7c <+16>: mov    x29, sp
    0x18e390d80 <+20>: bl     0x18e3757b4               ; cerror_nocancel
    0x18e390d84 <+24>: mov    sp, x29
    0x18e390d88 <+28>: ldp    x29, x30, [sp], #16
    0x18e390d8c <+32>: ret    

```

What React Native version does it support exactly? 
I currently have to use RN 0.32.1.

---
"react": "15.3.0"
"react-native": "^0.32.1"
"react-native-awesome-card-io": "^0.4.0
iOS 10 (device)

**Comment by Kerumen** [comment]
Yes, if you read the log you should see this:

> This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

I should document this in the README.

On a side note, this package only supports the latest version of React Native. I can't guarantee it will work on previous versions. You can try to install previous versions if the latest doesn't work on your RN version.
