### ISSUE TITLE
jest test Cannot read property 'DETECTION_MODE' of undefined

### ISSUE THREAD

**Issue by RupamShaw** [Kerumen/react-native-awesome-card-io#131]
react-native app works fine.
"react-native-awesome-card-io": "^0.8.2" 
added in root declare module "react-native-awesome-card-io" {.....} full typescript .. .d.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'DETECTION_MODE' of undefined

      at Object.<anonymous> (node_modules/react-native-awesome-card-io/CardIOView.ios.js:46:576)
      at Object.<anonymous> (node_modules/react-native-awesome-card-io/index.js:1:512)
can you please let me know how to proceed for test

**Comment by pntlhk** [comment]
Any updates?

**Comment by tomasswood** [comment]
Add the following to your jest set up file
```
jest.mock('react-native-awesome-card-io', () => {
  return {
    DETECTION_MODE: 'IMAGE_AND_NUMBER',
  }
});

**Comment by pntlhk** [comment]
I didn't tried add your code sample, but i added 
```js
jest.mock('react-native-awesome-card-io', () => ({
  CardIOUtilities: {
    preload: jest.fn(() => Promise.resolve('the response')),
  },
}));
```
and it's work for me

**Comment by Kerumen** [comment]
It seems that there are several solutions to the problem here. Closing!
