### ISSUE TITLE
Cannot read property 'DETECTION_MODE' of undefined

### ISSUE THREAD

**Issue by sherryxiao1988** [Kerumen/react-native-awesome-card-io#14]
Hi Yann,
@Kerumen 
I am trying to use this cool component in my react native app. I basically copy pasted the code for CardIOModule, and then got this error.

My react native version is 0.35.0. Do you know what's happening?

Thanks.
Shundan

![image](https://cloud.githubusercontent.com/assets/1202426/19777402/a384b11a-9caa-11e6-915b-3814d265826e.png)

**Comment by Kerumen** [comment]
Did you use the `DETECTION_MODE` constant?

**Comment by sherryxiao1988** [comment]
Nope. Deleting the example code and only importing this library throws this error as well.

**Comment by Kerumen** [comment]
I can't reproduce. Do you use the latest version of this module (`v0.4.0`)?

PS: This module is not well-suited to be tested in an emulator as it lacks a camera.

**Comment by sherryxiao1988** [comment]
works now! it was the version issue. I accidentally linked to the Kerumen/react-native-awesome-card-io version. It works fine after updating to v0.4.0. Closing this issue. Thanks for your help!

**Comment by lifuzu** [comment]
+1

[error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'CardIOUtilities.DETECTION_MODE')
[fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'CardIOUtilities.DETECTION_MODE')

**Comment by mo-solnet** [comment]
For future reference: you get this error if you haven't linked the library.
