### ISSUE TITLE
Issues with Scanning 

### ISSUE THREAD

**Issue by luckycharm313** [Kerumen/react-native-awesome-card-io#140]
I tried to run this package to scan a credit card. The success completion handler is never getting executed. This is happening only when I try to scan the card. Enter Manually option is working without any issues.

"react": "16.6.1",
"react-native": "0.57.7",
"react-native-awesome-card-io": "^0.8.2",

Please see code here: 
https://prnt.sc/on2gbh

Let me know if there is any suggestions.

**Comment by lucaspedroso26** [comment]
I am getting the same, When I click and the click action call the CardIOModule.scanCard() just says that null is not an object, but don't even now where this is this null he is loading. 

I am using this package inside an Expo project.

**Comment by jigaryadav** [comment]
I m also getting the issue with scan when I call the function card is not dictating properly I have to do so many times

**Comment by Pushpak-123** [comment]
I also faced same issue for normal card. I found that it works for emboss card. It scan and provide the result properly.

**Comment by ankitgauravapporio** [comment]
I am in desperate need , please solve this issue , can able to scan, thank you

**Comment by bingle87** [comment]
@luckycharm313 Did you get this figured out. I cant get the card to scan just keeps saying it will automatically scan the card

**Comment by minhnguyenwp** [comment]
@luckycharm313 I have faced the same issue. Did you find out how can we fix it?

**Comment by MUNEENDRA2019** [comment]
> I am getting the same, When I click and the click action call the CardIOModule.scanCard() just says that null is not an object, but don't even now where this is this null he is loading.
> 
> I am using this package inside an Expo project.

hii  lucas  i have faced the same issue.did you find out the solution..??

**Comment by Kerumen** [comment]
Can you try with the [last version](https://www.npmjs.com/package/react-native-awesome-card-io/v/0.9.0) of the library?
If it doesn't fix the problem, feel free to reopen the issue with a reproduction, I'll investigate!

**Comment by lucaspelle1909** [comment]
I am facing same issue, with the last version (0.9.0), and Expo sdk 39
