### ISSUE TITLE
[iOS 13] Problem with dark mode

### ISSUE THREAD

**Issue by retyui** [Kerumen/react-native-awesome-card-io#146]
When dark mode enabled a placeholder text of TextInput don't visible 

![card](https://user-images.githubusercontent.com/4661784/67482645-bf6cf300-f66c-11e9-9543-278d0f741202.jpg)

**Comment by alanbonachella** [comment]
the same issue

**Comment by alanbonachella** [comment]
+ 1

**Comment by alanbonachella** [comment]
+1

**Comment by gitstud** [comment]
Also seeing this, I'm looking at the code and trying to find where we might be able to pass our own styles for the manual entry form.  I'm not really a swift dev so this is quite difficult for me.  If anyone knows what file I should be looking at to edit the form styles I can write the bridge for it and submit a PR

**Comment by pimJNGNL** [comment]
+1

**Comment by Kerumen** [comment]
Unfortunately, this is a problem on the SDK itself. But the SDK is [now archived](https://github.com/card-io/card.io-iOS-SDK) so there is not much we can do..
