### ISSUE TITLE
[iOS] Crash on open with SIGABRT

### ISSUE THREAD

**Issue by pdrlima** [Kerumen/react-native-awesome-card-io#147]
I lost some time looking for this so putting it out there in hopes it can help someone.

In order for it to work on iOS you need to add NSCameraUsageDescription to your info.plist.

**Comment by Kerumen** [comment]
Thank you for this, I added the note on the README [recently](https://github.com/Kerumen/react-native-awesome-card-io/commit/e1d1e58fd3602771e5d951cf84ae592b671960a9).
