### ISSUE TITLE
guideColor expects an integer (for android)

### ISSUE THREAD

**Issue by richardgill** [Kerumen/react-native-awesome-card-io#15]
Hi There,

Thanks for this library, saved me a lot of time.

I noticed (on Android) that `guideColor` needs to be an int rather than a string when using `CardIOModule`. Do you know I how I do this conversion?

Thanks,

**Comment by Kerumen** [comment]
Sorry! I added the conversion. Now you can use it with a normal color string like `#ff0000`.
