### ISSUE TITLE
scanCard method not scanning expiry date and card holder name

### ISSUE THREAD

**Issue by sagar-chhatrola** [Kerumen/react-native-awesome-card-io#152]
`
CardIOModule
      .scanCard({
        hideCardIOLogo:true,
        usePaypalActionbarIcon:false,
        suppressConfirmation:true,
                suppressManualEntry:true,
        useCardIOLogo:false,
        requireCVV:false,
        scanExpiry:true,
        requireExpiry:true,
        requireCardholderName:true,
        detectionMode:'CardIODetectionModeCardImageAndNumber'

      })
`

**Comment by aaristotle75** [comment]
Any update on this?

**Comment by sankar9659** [comment]
Try like this,

 CardIOModule
            .scanCard()
            .then(async card => {
                Reactotron.log({ 'card details': card });
                // the scanned card
            })
            .catch((e) => {
                Reactotron.log({ 'error': e });
                // the user cancelled
            })

**Comment by fedarenchyk** [comment]
+1

**Comment by schultz9999** [comment]
Not working for me either. Getting 0/0 back. Card number works fine.

**Comment by Kerumen** [comment]
Can you try with the [last version](https://www.npmjs.com/package/react-native-awesome-card-io/v/0.9.0) of the library?
If it doesn't fix the problem, feel free to reopen the issue with a reproduction, I'll investigate!
