### ISSUE TITLE
iOS Linking ObjC not working on RN above 0.60

### ISSUE THREAD

**Issue by ognjenciric** [Kerumen/react-native-awesome-card-io#157]
iOS issue prevent awesome-card-io from being used in application and throws 
current issue. Besides that, it only scannes the expiry date and cardNumber.

![80373268-19a57580-8895-11ea-9987-bc51f846eea9](https://user-images.githubusercontent.com/16581294/80483363-42da0a80-8956-11ea-9288-562e4c32eadb.png)

**Comment by Kerumen** [comment]
This is now fixed in the last version! Don't hesitate to try it.
