### ISSUE TITLE
npm ERR! From:     https://registry.npmjs.org/react-native-awesome-card-io/-/react-native-awesome-card-io-0.5.0.tgz

### ISSUE THREAD

**Issue by raphkr** [Kerumen/react-native-awesome-card-io#16]
Every time i try installing the latest version i keep getting the npm error. Also tried cleaning cache and then using npm

**Comment by Kerumen** [comment]
I just tried and it's working well. I guess it's a problem on your side.
Maybe you are behind a proxy? Check your internet connection?
Try to install other packages.

Or it's a problem with the npm registry. Wait a few minutes and try again.

**Comment by raphkr** [comment]
Thanks

**Comment by julienvincent** [comment]
@Kerumen I am getting the exact same issue.

```
http://registry.yumochefs.com/react-native-awesome-card-io/-/react-native-awesome-card-io-0.5.0.tgz: unexpected end of file
```

**Comment by Kerumen** [comment]
@julienvincent It's working on my side. Because of the Card.io SDK the package is big, try again in few minutes and make sure your network is stable.

**Comment by julienvincent** [comment]
Hmm. It could be due to the package size, still a bit odd that I only experience this problem with this package. After a few more attempts the install eventually succeeded, but it will still occasionally fail even when running via circleci.

**Comment by Kerumen** [comment]
I'm sorry but I don't know what happen here and how I can fix it.

**Comment by julienvincent** [comment]
@Kerumen No idea either :P If I figure something out i'll let you know
