### ISSUE TITLE
library conflicting while pod install

### ISSUE THREAD

**Issue by mitjnextt** [Kerumen/react-native-awesome-card-io#161]
When Installing with another package called react-native-paypal-lib,
My pod install is failing, here is the output of pod install.

Analyzing dependencies
Downloading dependencies
Installing RNAwesomeCardIO (0.8.3)
[!] The 'Pods-Testapp' target has libraries with conflicting names: libcardio.a, libopencv_core.a, and libopencv_imgproc.a.

**Comment by wedusa** [comment]
Same

**Comment by wedusa** [comment]
Upgrading to 0.9.0-rc.1 helped me

**Comment by mitjnextt** [comment]
Thank you very much! It helped me too

**Comment by wedusa** [comment]
I must warn you that in this situation the latest version of the conflicting files will be used and there may be problems with libs who use an older version.
