### ISSUE TITLE
The callback scanCard() exists in module CardIOModule, but only one callback may be registered to a function in a native module

### ISSUE THREAD

**Issue by raphkr** [Kerumen/react-native-awesome-card-io#17]
I am getting this on android. The problem that occurs is that the card does get scanned once but then it just stays there forcing you to scan again.

**Comment by raphkr** [comment]
Im using RN 0.35. Testing on android lolipop. Let me know if u need any further info.

**Comment by Kerumen** [comment]
I can't reproduce with my Nexus 5X (Android N). Unfortunately I don't have any device with lower Android version.

Can you show the code that is not working?

**Comment by raphkr** [comment]
Firstly I would like to thank you for taking the time to reply. So let me explain my scenario. Basically I am looking to get the image of the card. Something what CardIOView lets u do for IOS. From checking the logs I can see that I can get the scanned image. However after scanning the view is suppose to close. But this does not happen. Instead it waits to be scanned a second time. 

On scanning the second time I get the error. Below is a sample of my code. It will be really great if you could throw in some suggestions for changes i need to make.

handleClose(cardImageData) {
      console.log('Card Image Data: ',cardImageData);
      this.props.onclose(cardImageData);
    }

    getCardView() {
      CardIOModule
        .scanCard({
          scanInstructions:`Hold the ${this.props.scanningFace} of card - It will scan automatically.`,
          suppressManualEntry: true,
          suppressConfirmation: true,
          hideCardIOLogo:true
        })
        .then(card => {
          console.log('card : ', card.cardImage);
          this.handleClose(card.cardImage);
        })
        .catch(err => logger.error(`Failed to scan digital card. Error message: ${err}`));
    }

    render() {
      return (
          <View style={styles.wrapper}>
              <TouchableOpacity onPress={this.props.close} style={{position: 'absolute', top:30, left: 30, height: 50, backgroundColor: 'transparent'}}>
                <Icon
                  name={'ios-close-outline'}
                  size={30}
                  color={'#fff'}
                  style={{width: 30, height: 30, marginTop:10, marginLeft:10}}
                />
              </TouchableOpacity>
              {Platform.OS === 'android' ? <View>{this.getCardView}</View>:

**Comment by Kerumen** [comment]
You are doing it wrong here. The `scanCard` method of the `CardIOModule` is not a view.

You have to call this method in a `Touchable` and it will present a new view automatically.

```jsx
 scanCard() {
    CardIOModule
      .scanCard({
        scanInstructions:`Hold the ${this.props.scanningFace} of card - It will scan automatically.`,
        suppressManualEntry: true,
        suppressConfirmation: true,
        hideCardIOLogo: true
      })
      .then(card => {
        console.log('card : ', card.cardImage);
        this.handleClose(card.cardImage);
      })
      .catch(err => logger.error(`Failed to scan digital card. Error message: ${err}`));
  }

  render() {
    return (
      <View>
        <TouchableOpacity onPress={this.scanCard}>
          <Text>Scan card!</Text>
        </TouchableOpacity>
      </View>
    );
  }
```

And you can use the same code for iOS.

Let me know if it solves the problem!

**Comment by raphkr** [comment]
Thanks for that. Works perfectly.
