### ISSUE TITLE
Implicit declaration of function 'RCTPresentedViewController' is invalid in C99

### ISSUE THREAD

**Issue by JakielaAdam** [Kerumen/react-native-awesome-card-io#18]
I'm having some trouble building my iOS project with the react-native-awesome-card-io files included. I followed the installation instructions but I'm getting the following build error in on line 116 of `RCTCardIOModule.m`.

`RCTCardIOModule.m:116:44: Implicit declaration of function 'RCTPresentedViewController' is invalid in C99`

`    UIViewController *rootViewController = RCTPresentedViewController();
`

Any ideas on how I can solve this? I am not very failure with Objective C so I apologize if this is a trivial issue.

**Comment by Kerumen** [comment]
Which version of React Native do you use?

Do you use the latest version of the library?

**Comment by JakielaAdam** [comment]
React Native:  0.23.1
react-native-awesome-card-io: 0.5.0

**Comment by Kerumen** [comment]
Oh well.

This library only supports the latest version of React Native. And your version is very old. Upgrade to the latest (0.36) and it should work.
