### ISSUE TITLE
App crashing on android M

### ISSUE THREAD

**Issue by raphkr** [Kerumen/react-native-awesome-card-io#19]
As soon as scanning starts, the app cashes on M.

**Comment by Kerumen** [comment]
It works perfectly on my side. Please provide some detailed code of what are you trying to do.

**Comment by raphkr** [comment]
Below is the stack trace for the error.

1-05 19:44:58.917 14677 14677 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49463195, result=13274388, data=Intent { cmp=com.evivernappv0/io.card.payment.DataEntryActivity }} to activity {com.evivernappv0/com.evivernappv0.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:154)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at com.cardio.RNCardIOModule.bitMapToString(RNCardIOModule.java:131)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at com.cardio.RNCardIOModule.onActivityResult(RNCardIOModule.java:121)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:226)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:620)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6470)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
11-05 19:44:58.917 14677 14677 E AndroidRuntime: 	... 9 more
11-05 19:44:58.931  1877  5555 W ActivityManager:   Force finishing activity com.evivernappv0/.MainActivity

**Comment by Kerumen** [comment]
And what is your JS code?

**Comment by raphkr** [comment]
Below is a part of my code


getCardView() {
      CardIOModule
        .scanCard({
          scanInstructions:`Hold the ${this.props.scanningFace} of card - It will scan automatically.`,
          suppressManualEntry: true,
          suppressConfirmation: true,
          hideCardIOLogo:true
        })
        .then(card => {
          console.log('card : ', card.cardImage);
          this.saveCardInfo(card.cardImage);
        })
        .catch(err => logger.error(`Failed to scan digital card. Error message: ${err}`));
    }

    getCardViewFor(face) {
      return (
          <View style={styles.cardWrapper}>
              <Image
                style={styles.imageWrapper}
                source={this.getImage(face)}>

                  <TouchableOpacity style={styles.captureView}
                    onPress= {this.captureCard.bind(this,face)} >
                        <View>{this.getIcon(face, 'icon')}</View>
                        <View  style={styles.textWrapper}>{this.getIcon(face, 'text')}</View>
                  </TouchableOpacity>
              </Image>


Get card view gets called from captureCard. Basically, I wrapped it in the Touchable opacity component as u specified in the previous issue.
Let me know if u need any thing more

**Comment by Kerumen** [comment]
Can you show captureCard?

**Comment by raphkr** [comment]
Sorry for the late reply. Below is the code for the same.

captureCard(scanningFace) {
      Permissions
        .getPermissionStatus('camera')
        .then(response => {
          if (response === 'undetermined') {
            Permissions.requestPermission('camera');
          } else if (response === 'authorized') {
            if (scanningFace === 'back' && this.state.isBackOfCardCaptured) {
              return;
            }
            if (scanningFace === 'front' && this.state.isFrontOfCardCaptured) {
              return;
            }
            console.log('Scanning Face: ', scanningFace);
            this.setState({ scanningFace });

            if (Platform.OS === 'ios') {
                this.refs.detail.open();
            } else {
                this.getCardView();
            }

          } else {
            Alert
              .alert(
                'Digital Card',
                'Please allow Camera for this app to store your digital card.',
                [{
                  text: 'Cancel'
                }, {
                  text: 'Open Settings',
                  onPress: () => {
                    RNUtils.openSettings();
                  }
                }]
              );
              logger.warn('Camera permissions is not present');
          }
        });
    }

**Comment by raphkr** [comment]
I think I figured the solution. I had removed the CardActivityIO.EXTRA_SCAN_RESULT from the package. Have fixed this now.
No crashes. Tnx for the help
