### ISSUE TITLE
CardIOUtilities.CAN_READ_CARD_WITH_CAMERA = false

### ISSUE THREAD

**Issue by markflorisson** [Kerumen/react-native-awesome-card-io#21]
The procedure of install react-native-awesome-card-io and doing 'react-native link' used to work, but it is no longer showing the card.io scanner. I'm wondering if this is a permission issue?

**Comment by Kerumen** [comment]
What device are you using? Which operating system?

**Comment by markflorisson** [comment]
I'm running Android 6.0 (Marshmallow), installing from Linux (Ubuntu 16.04). I'm using react-native 0.38.0.

**Comment by Kerumen** [comment]
Which version of the library are you installing? 
React Native `0.38.0` is supported until `0.5.0`.
`0.6.0` is targeted for `0.39.0` and beyond.

**Comment by markflorisson** [comment]
I'm using 0.5.0. But I can try upgrading RN with RN-awesome-card-io >= 0.6.0 and seeing if the issue persists, thanks!

**Comment by Kerumen** [comment]
I released 0.6.1 last week. It contains the latest card.io SDK which fixed a bug with some Android devices. Try it out!

**Comment by markflorisson** [comment]
Works perfectly, thanks so much!
