### ISSUE TITLE
Cannot read property 'scanCard' of undefined

### ISSUE THREAD

**Issue by mikeaxle** [Kerumen/react-native-awesome-card-io#22]
I am getting the following error when i call the scanCard() method:

Cannot read property 'scanCard' of undefined

**Comment by mikeaxle** [comment]
sorry, just needed to recompile after switching git branch of my app lol.

**Comment by luskin** [comment]
If anyone else is running into this problem make sure that you import `import com.cardio.RNCardIOPackage;` to your MainApplication.java on android and add:

```
new RNCardIOPackage()
```

to your react package arraylist in your MainApplication implementation

**Comment by navneetgarggate6** [comment]
ExceptionsManager.js:63 Cannot read property 'scanCard' of undefined
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:69
reportFatalError @ error-guard.js:42
__guardSafe @ MessageQueue.js:316
callFunctionReturnFlushedQueue @ MessageQueue.js:115
(anonymous) @ debuggerWorker.js:70

**Comment by navneetgarggate6** [comment]
I am getting same issue in android

ExceptionsManager.js:63 Cannot read property 'scanCard' of undefined
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:69
reportFatalError @ error-guard.js:42
__guardSafe @ MessageQueue.js:316
callFunctionReturnFlushedQueue @ MessageQueue.js:115
(anonymous) @ debuggerWorker.js:70
