### ISSUE TITLE
undefined is not an object (evaluating 'CardIOUtilities.DETECTION_MODE')

### ISSUE THREAD

**Issue by lifuzu** [Kerumen/react-native-awesome-card-io#25]
[error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'CardIOUtilities.DETECTION_MODE')
[tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'CardIOUtilities.DETECTION_MODE')

react-native-cli: 2.0.1
react-native: 0.41.2

in package.json
"react-native-awesome-card-io": "^0.6.1"

**Comment by Kerumen** [comment]
It seems you forgot to run `react-native link react-native-awesome-card-io`.
