### ISSUE TITLE
undefined is not an object (evaluating 'CardIOUtilities.DETECTION_MODE')

### ISSUE THREAD

**Issue by dejakob** [Kerumen/react-native-awesome-card-io#28]

**Comment by dejakob** [comment]
Nevermind, forgot to link and restart the packager...

**Comment by nating** [comment]
I'm having this issue as well. Restarting the packager doesn't seem to be working... 😅

**Comment by netors** [comment]
Same issue, not working
![img_6697](https://user-images.githubusercontent.com/893833/29532343-84cd65c2-8661-11e7-9266-cb8290348f3e.PNG)

**Comment by pcooney10** [comment]
@netors i am not 100% certain, but i do not think this library is compatible with expo due to the reliance on `react-native-link`

**Comment by Kerumen** [comment]
@netors As @pcooney10 said, you can't use this library with expo. You have to run `exp detach` to be able to run `react-native link`

**Comment by duranmla** [comment]
Problem here may be related to this topic: https://docs.expo.io/versions/latest/guides/expokit.html#ios thing is that I am not sure which will be the "relative path" to add in Xcode so the library will work, cause it suppose that if we eject from react native to work with expoKit we still be able to add this sort of libraries

**Comment by dauane** [comment]
I am getting this same issue. Was anyone able to solve it?

**Comment by ntk860** [comment]
same here

**Comment by ntk860** [comment]
@Kerumen can you reopen this issue? I am having serious problems with that

**Comment by Azeez09** [comment]
Still I am facing the same issue in iOS. Not sure why this issue is closed. Was there any fix or workaround for this?
In Android, I am able to read only card number. So, overall I couldn't use this package in both ios and android. Please suggest.

**Comment by ntk860** [comment]
I dont understand why it was closed either. I am using exp, and I already did detach, but still not working

**Comment by pcooney10** [comment]
@ntk860 @Azeez09 regardless of using Expo, there are sometimes issues with `react-native link`. In order solve this, you will need to link manually.

This is mentioned in the [ExpoKit docs](https://docs.expo.io/versions/latest/guides/expokit.html#ios), and explained pretty thoroughly in the [RN Docs](https://facebook.github.io/react-native/docs/linking-libraries-ios.html).

For iOS, this can be as simple as adding a dependency to your `Podfile` and running `pod install`, or manually adding & linking the Library in XCode and verifying the Header Search Paths. For Android,  somewhat similar steps are required, and (I believe) you should be looking to the `build.gradle` and `AndroidManifest.xml` files.

I do not currently use this lib, so I am not sure what the specific dependences you need to get it to work. But in the spirit of teaching one to fish, you can look to some popular libs like [`react-native-maps`](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md), [`react-native-vector-icons`](https://github.com/oblador/react-native-vector-icons#installation), and [`react-native-camera`](https://github.com/react-native-community/react-native-camera#getting-started) that have detailed instructions for manual installation where you will hopefully be able to glean more information on this topic.

**Comment by ntk860** [comment]
@pcooney10 thank you so much

**Comment by oliver-auka** [comment]
Are there any instructions to link this manually for those of us that are using Native navigation projects or with broken linker functionality?

**Comment by leonidez** [comment]
I had the same problem and I found the steps to link this project manually here: https://facebook.github.io/react-native/docs/linking-libraries-ios
