### ISSUE TITLE
Hangs on loadRequestedDeos

### ISSUE THREAD

**Issue by PuzzleVerse** [Kerumen/react-native-awesome-card-io#33]
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/7.9.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'react-native-awesome-card-io',
npm verb cli   '--save',
npm verb cli   '--verbose' ]
npm info using npm@4.2.0
npm info using node@v7.9.0
npm verb request uri https://registry.npmjs.org/react-native-awesome-card-io
npm verb request no auth needed
npm info attempt registry request try #1 at 4:50:41 pm
npm verb request id e9ab3ef35a347917
npm verb etag W/"588befde-80ad"
npm verb lastModified Sat, 28 Jan 2017 01:11:58 GMT
npm http request GET https://registry.npmjs.org/react-native-awesome-card-io
npm http 304 https://registry.npmjs.org/react-native-awesome-card-io
npm verb headers { date: 'Mon, 24 Apr 2017 06:50:42 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"588befde-80ad"',
npm verb headers   age: '118',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-syd1625-SYD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1493016642.106106,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/react-native-awesome-card-io from cache
npm verb get saving react-native-awesome-card-io to /Users/piotrsuwara/.npm/registry.npmjs.org/react-native-awesome-card-io/.cache.json
npm verb correctMkdir /Users/piotrsuwara/.npm correctMkdir not in flight; initializing
npm verb cache add spec react-native-awesome-card-io
npm verb addNamed "latest" is being treated as a dist-tag for react-native-awesome-card-io
npm info addNameTag [ 'react-native-awesome-card-io', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/react-native-awesome-card-io not in flight; fetching
npm verb get https://registry.npmjs.org/react-native-awesome-card-io not expired, no request
npm verb addNamed "0.6.1" is a plain semver version for react-native-awesome-card-io
npm verb addRemoteTarball https://registry.npmjs.org/react-native-awesome-card-io/-/react-native-awesome-card-io-0.6.1.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/react-native-awesome-card-io/-/react-native-awesome-card-io-0.6.1.tgz',
npm verb addRemoteTarball   '2e1a3f8a186ba560f87e19497bdf36a24a421079' ]
npm info retry fetch attempt 1 at 4:50:42 pm
npm info attempt registry request try #1 at 4:50:42 pm
npm http fetch GET https://registry.npmjs.org/react-native-awesome-card-io/-/react-native-awesome-card-io-0.6.1.tgz
npm http fetch 200 https://registry.npmjs.org/react-native-awesome-card-io/-/react-native-awesome-card-io-0.6.1.tgz
⸨    ░░░░░░░░░░░░░░⸩ ⠧ loadRequestedDeps: http fetch 200 https://registry.npmjs.org/react-native-awesome-card-io/-/react-native-awesome-card-io-0.6.1.tgz

No progress after this point.

**Comment by Kerumen** [comment]
Hello,

I must publish the card.io iOS SDK in the npm package that's why the installation is a bit long.
You must have a good connection and let it run, the package will successfully install after a while.

Sorry for the trouble, I will try to find a better solution.
