### ISSUE TITLE
Header support for both RN < 0.40 and >= 0.40

### ISSUE THREAD

**Issue by peacechen** [Kerumen/react-native-awesome-card-io#34]
To better support the breaking header path change in React Native 0.40, the imports should be conditional in order to support both pre-0.40 and 0.40+ releases.  I'll submit a PR for this.  How quickly are PR's considered for merge?

**Comment by Kerumen** [comment]
As soon as I review it and find it relevant.

Go ahead, it's a good idea! :)

**Comment by peacechen** [comment]
Created PR #35

**Comment by Kerumen** [comment]
Fixed by 5a28c34b7e0be91b58d98d4ecf0b4a559f1accb4
