### ISSUE TITLE
preload() is undefined

### ISSUE THREAD

**Issue by siloebb** [Kerumen/react-native-awesome-card-io#42]
![image](https://user-images.githubusercontent.com/5496305/27645214-f0d73198-5bfb-11e7-8961-6d53041172fe.png)

I can't run the 'CardIOModule' because I ever receive undefined. I has linked, I reinstall, I has excluded the 'node_modules'.

How can I use the lilbrary?

**Comment by Kerumen** [comment]
Did you ran `./gradlew clean`?

**Comment by tetsu** [comment]
I got the same error. And ./gradlew clean doesn't solve this problem. Can it be related to react native version?

**Comment by GregTheGreek** [comment]
The docs say .preload() is iOS only, you are trying to load it on Android. Check for the device or don't use .preload()

**Comment by Kerumen** [comment]
Thanks @GregTheGreek, was a bit tired when I first answered.
He's right, `preload` is iOS only.

```js
if (Platform.OS === 'ios') {
  CardIOUtilities.preload();
}
```
