### ISSUE TITLE
Android Build Failure

### ISSUE THREAD

**Issue by nicholasstephan** [Kerumen/react-native-awesome-card-io#43]
Module works perfectly on iOS, but on android I'm getting the following build errors:

```
Error:(19, 8) error: RNCardIOModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
Error:(102, 3) error: method does not override or implement a method from a supertype
Error:(124, 3) error: method does not override or implement a method from a supertype
Error:Execution failed for task ':react-native-awesome-card-io:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

This is using react-native-awesome-card-io ^0.6.4, and react-native ^0.45.1.

**Comment by Kerumen** [comment]
Did you ran `./gradlew clean` in the `android` folder?

**Comment by nicholasstephan** [comment]
Thanks. `clean` goes through fine, but I'm still getting the same error. But when I start a new react native project and install your card-io, it seems to work fine, so the issue must be somewhere else. Thanks again.
