### ISSUE TITLE
Request Number of Scans

### ISSUE THREAD

**Issue by LMestre14** [Kerumen/react-native-awesome-card-io#44]
Is it possible for the component to receive a number of scans? For android purposes, because what I intend with the component is for the user to be able to read more than one card and at the moment after the first successful read, it doesn't let the user to read again

**Comment by Kerumen** [comment]
It is not possible with the SDK. You can solve this by calling `scan` again in the `then`:

```js
CardIOModule
  .scanCard()
  .then(card => {
    // the scanned card
    return CardIOModule.scanCard();
  })
  .then(card => {
    // the new scanned card
  })
```
