### ISSUE TITLE
Android says "keyboard"

### ISSUE THREAD

**Issue by mirandasaari1** [Kerumen/react-native-awesome-card-io#47]
The option on the card scanner for ios says "Enter Manually", but android version says "Keyboard...". Is there a way to change the verbiage for android so the user knows where they will be redirected to? Can not seem to find the text for these in the code.

**Comment by Kerumen** [comment]
That's not currently possible with the Android SDK sorry.

**Comment by chapeljuice** [comment]
Would love to have the option to change this wording & the style of the button too.

**Comment by Kerumen** [comment]
You can make a PR on the appropriate repo, the [card.io Android SDK](https://github.com/card-io/card.io-Android-source).
This library is only a wrapper and can't offer more functionalities.

**Comment by chapeljuice** [comment]
Oh, gotcha. Thanks @Kerumen !
