### ISSUE TITLE
CardIOView.android.js is not importing Text and View

### ISSUE THREAD

**Issue by tetsu** [Kerumen/react-native-awesome-card-io#48]
![missingview](https://user-images.githubusercontent.com/843151/28214293-a2d64132-68e4-11e7-8003-ac470804594a.png)

There is one simple error.

In `CardIOView.android.js`, you forgot to import `View` and `Text` from `react-native`.

Thanks!

**Comment by anishclarion** [comment]
Yes this is reproduced in my project also.

**Comment by anishclarion** [comment]
I found solution!!!, The CardIOView component will not work on Android, that is clearly mentioned in the doc. Please user 'CardIOModule'
