### ISSUE TITLE
Error o Running app: error: package com.cardio does not exist import com.cardio.RNCardIOPackage;

### ISSUE THREAD

**Issue by anishclarion** [Kerumen/react-native-awesome-card-io#49]
Ima getting the below error when I am running the app, after installing the package react-native-awesome-card-io. I have executed the link command also but still the issue I am facing.

MainApplication.java:6: error: package com.cardio does not exist
import com.cardio.RNCardIOPackage;

![28421275-495c541e-6d82-11e7-8ea4-044681cca196](https://user-images.githubusercontent.com/16605830/28421527-1500f610-6d83-11e7-8713-314fb15f657a.png)

**Comment by anishclarion** [comment]
Fixed by doing the following. The following code is not injecting while we run react-native link. so if you can add this on read me doc it will help others if they are facing this issue.

Insert the following lines inside the dependencies block in android/app/build.gradle:
  compile project(':react-native-awesome-card-io')

**Comment by andrisole92** [comment]
Add this to README.MD

**Comment by Kerumen** [comment]
The `react-native link` command should add this step.
