### ISSUE TITLE
iOS Camera doesn't show up

### ISSUE THREAD

**Issue by micksabox** [Kerumen/react-native-awesome-card-io#50]
I'm using this module via [react-native-checkout](https://github.com/z-dev/react-native-checkout/blob/master/src/components/scanCard/index.js)

When I first installed the app, I had no problems using the camera to scan a card. However, at some point, whenever a user tries to scan a card, the camera view does not appear. I am not sure if this is a regression introduced in a new version of iOS.

The link above includes the coded implementation of this module. It is fairly straightforward. I have added a privacy usage description for the camera, but after the user accepts the prompt, no camera is shown.

**Comment by micksabox** [comment]
This is the log that displays:
```
2017-07-21 14:25:58.523977-0400 ***[1042:291649] [Common] _BSMachError: port cc6b; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2017-07-21 14:25:58.524539-0400 ***[1042:291649] [Common] _BSMachError: port cc6b; (os/kern) invalid name (0xf) "Unable to deallocate send right"
```

**Comment by anishtr4** [comment]
Even I am facing same issue, did you got any solution ?

**Comment by Kerumen** [comment]
Which RN version are you using?

**Comment by micksabox** [comment]
I was using 42.x when it did not work. I have not yet tried the latest RN version to see if it works there.

**Comment by celso-henrique** [comment]
Did you tried to add permission to camera on info.plist file?
```
  <key>NSCameraUsageDescription</key>
  <string>${PRODUCT_NAME} Camera Usage</string>
```

**Comment by Kerumen** [comment]
Closing since the OP remains silent for one month.
Let me know if you still have problems and I can reopen :)
