### ISSUE TITLE
Camera doesn't show up in iOS 

### ISSUE THREAD

**Issue by anishtr4** [Kerumen/react-native-awesome-card-io#57]
Initially we were ablke to scan the card after few days when i checked the same scan feature camera does't show up. I have tested in iphone 5:IOS 10.3.2, Iphone 7:IOS 10.3.3

**Comment by Kerumen** [comment]
Do you have the latest lib version? What is your RN version?

Can you show me how do you call it?

**Comment by celso-henrique** [comment]
Did you tried to add permission to camera on info.plist file?
```
  <key>NSCameraUsageDescription</key>
  <string>${PRODUCT_NAME} Camera Usage</string>
```

**Comment by Kerumen** [comment]
Closing since the OP remains silent since one month. Let me know if you still have problems and I can reopen :)
