### ISSUE TITLE
[ Android ] React Native 0.47 breaking change

### ISSUE THREAD

**Issue by sonbuiGFD** [Kerumen/react-native-awesome-card-io#58]
Error occurs when I run react-native run-android
full error:

\node_modules\react-native-awesome-card-io\android\src\main\java\com\cardio\RNCardIOPackage.java:23: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-awesome-card-io:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-awesome-card-io:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

I believe that issue cause by React Native 0.47 breaking change.

Remove unused createJSModules calls (https://github.com/facebook/react-native/releases/tag/v0.47.0)

**Comment by jesster2k10** [comment]
I've got the same issue

**Comment by jesster2k10** [comment]
I saw on another issue that it was fixed in a later version

**Comment by luchoster** [comment]
#54 fixed this issue.

**Comment by Alex-Mann** [comment]
I am also having this issue, using `react-native-awesome-card-io@0.6.4`

**Comment by Kerumen** [comment]
Hey, I've just published `v0.7.0` with latest master changes.
