### ISSUE TITLE
[Android] Hide captured image from users

### ISSUE THREAD

**Issue by fokoz** [Kerumen/react-native-awesome-card-io#59]
On iOS, setting `scannedImageDuration: false` makes the captured image disappear really quickly.

The reason I set up like this, because I think users will feel like their credit cards were captured somewhere and it feel unsafe if they see the captured image. However, this setting is only on iOS, so I am curious about Android if it can hide the captured image from users's eyes and return immediately like iOS does ? by the way, right now I don't have time to test yet on Android, sorry if it has already been able to do this.

Thank you.

**Comment by Kerumen** [comment]
Nope sorry, there is no available method in the card.io Android SDK.
