### ISSUE TITLE
CardIOUtilities.canReadCardWithCamera Usage

### ISSUE THREAD

**Issue by sbycrosz** [Kerumen/react-native-awesome-card-io#6]
Hi @Kerumen,
Thanks for the great library!

The current version requires a callback 

```js
CardIOUtilities.canReadCardWithCamera(canReadWithCamera => {
    // show or hide the scan button
});
```

Should we expose them as native constant since they're unlikely to change while the app is running?

Cheers,
Sam

**Comment by Kerumen** [comment]
I did this because the SDK provides a function and this is currently then only way to return a value from a function in a React Native bridge.
But I'm open to suggestions, if you want to expose this as a native constant, feel free to send a PR!
