### ISSUE TITLE
Card having name, not getting scanned

### ISSUE THREAD

**Issue by kaberibasu** [Kerumen/react-native-awesome-card-io#60]
Hi,
My react native version is - 0.41.0
react native awesome card io version is- 0.6.2

I am using CardIOModule- 
```
CardIOModule
        .scanCard()
        .then((card: any) => {
          // the scanned card
          console.log("card", card);
          this.setCardValuesInState(card);
        })
        .catch((err: any) => {
          // the user cancelled
          console.log("error is", err);
        });
```
Its working fine with cards not having name in it, but not able to scan cards having name in it.

**Comment by Kerumen** [comment]
I'm sorry but this lib is only a wrapper to the SDK.
If you encounter bugs, you can directly report them [here](https://github.com/card-io/card.io-Android-SDK) for the Android one and [here](https://github.com/card-io/card.io-iOS-SDK) for the iOS one.
