### ISSUE TITLE
Does not build on Android with buildToolsVersion 25

### ISSUE THREAD

**Issue by mo-solnet** [Kerumen/react-native-awesome-card-io#62]
The latest Android Studio and Gradle require `buildToolsVersion 25` and this library does not build with this version.

**Scenario**: A project is using this library as a dependency. The project updates to latest RN (0.47.2) as well as Android Studio 2.2.3. This library will prevent building the project because the `buildToolsVersion` is too low.

**Comment by Kerumen** [comment]
Fixed by https://github.com/Kerumen/react-native-awesome-card-io/commit/6f964e7b2d4c1e1fff1bb29c41819cd4a19ec6b7
