### ISSUE TITLE
Not working on Android, works on IOS

### ISSUE THREAD

**Issue by ashimiblessing** [Kerumen/react-native-awesome-card-io#63]
I can't seem to get this library to work on android. I was able to build the project successfully but any attempt to use it (  CardIOModule.scanCard()) give the following error:

undefined is not a function (evaluating '_reactNativeAwesomeCardIo.CardIOUtilities.preload()')
componentWillMount
    scanCard.js:77:4
<unknown>
    ReactNativeStack-dev.js:1652:19
measureLifeCyclePerf
    ReactNativeStack-dev.js:1610:15
mountComponent
    ReactNativeStack-dev.js:1651:57
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
.
.
.
The remaining part removed for brevity.

React native version is 0.47.2

Any ideas?

**Comment by Kerumen** [comment]
`preload` is iOS only ([doc](https://github.com/Kerumen/react-native-awesome-card-io#methods-1)). You have to check the `Platform` you are onto before calling it, like this:

```js
import { Platform } from 'react-native'
import { CardIOUtilities } from 'react-native-awesome-card-io';

if (Platform.OS === 'ios') {
  CardIOUtilities.preload()
}
```

I will update the README with this sample.

**Comment by ashimiblessing** [comment]
Aww. Okay, thank you.
