### ISSUE TITLE
Looking for a doc to install card.io to an existing project.

### ISSUE THREAD

**Issue by ODelibalta** [Kerumen/react-native-awesome-card-io#64]
I thought installing this lib was enough but I think I am wrong. I need to install card.io first correct? I am very scared editing pods on an existing project. it never worked to my advantage. Is there a clear documentation somewhere? 

![screen shot 2017-09-17 at 4 58 27 pm](https://user-images.githubusercontent.com/4956550/30525313-9dd89bfe-9bc9-11e7-9f78-f0e7f3ce00ca.png)

**Comment by Kerumen** [comment]
No, you don't need to install any pods the iOS is directly embedded ([here](https://github.com/Kerumen/react-native-awesome-card-io/tree/master/ios/CardIO)).

Don't forget to run `react-native link` to restart your packager and you should be fine.
Tell me if it solves your problem :)

**Comment by Kerumen** [comment]
Assumed resolved.

**Comment by chukzzy** [comment]
@Kerumen This doesnt resolve it for me. Thanks.
