### ISSUE TITLE
Cannot build for Android

### ISSUE THREAD

**Issue by mormrod** [Kerumen/react-native-awesome-card-io#65]
I have been building for iOS in my react native project and the card.io reader works perfectly, thank you.  The problem is, as soon as I try and build for Android I get the following message:

<img width="1280" alt="screen shot 2017-09-25 at 15 56 11" src="https://user-images.githubusercontent.com/11736058/30815191-520b77f4-a20a-11e7-9d1c-45cc3680a81c.png">

What am I doing wrong?

**Comment by Kerumen** [comment]
What is your React Native version?

**Comment by mormrod** [comment]
Thanks for replying, it's version 0.44 currently

**Comment by Kerumen** [comment]
This library only supports the latest React Native version. If you have an older RN version, use a previous tag of the library. For 0.44, `v0.6.4` should work.
```
npm install --save react-native-awesome-card-io@0.6.4
```

**Comment by mormrod** [comment]
Many thanks. I will give that a try
