### ISSUE TITLE
App crashes when scanner opens

### ISSUE THREAD

**Issue by dvuvne** [Kerumen/react-native-awesome-card-io#66]
Hello Team

I am having an issue that happens everytime I open the app. It is unclear what the exact error is but I am guessing it might something related to getting camera permissions on iOS. Could you please assist with this?

**Comment by adpuckett87** [comment]
I had this same issue, I added the following to Info.plist and it fixed it. 

<key>NSCameraUsageDescription</key>
<string>ADD YOUR USAGE DESCRIPTION HERE</string>

**Comment by amlord** [comment]
We've had a similar thing, and it turned out to be a permissions issue - if a user has denied access to the camera, then the component tries to access it, the app will crash.

The previous comment will prompt the device to ask for permissions, but only on the first attempt. This means that if a user denies access, the next time they come to use the functionality they'll get the same issue.

Our solution was to check for camera permissions & show a screen telling the user how to update their app settings.

**Comment by dauane** [comment]
That was exactly the problem. I needed to check camera permissions before opening the scanner.

**Comment by jbtobar** [comment]
> We've had a similar thing, and it turned out to be a permissions issue - if a user has denied access to the camera, then the component tries to access it, the app will crash.
> 
> The previous comment will prompt the device to ask for permissions, but only on the first attempt. This means that if a user denies access, the next time they come to use the functionality they'll get the same issue.
> 
> Our solution was to check for camera permissions & show a screen telling the user how to update their app settings.

What did you use to check camera permissions?

**Comment by amlord** [comment]
> > We've had a similar thing, and it turned out to be a permissions issue - if a user has denied access to the camera, then the component tries to access it, the app will crash.
> > The previous comment will prompt the device to ask for permissions, but only on the first attempt. This means that if a user denies access, the next time they come to use the functionality they'll get the same issue.
> > Our solution was to check for camera permissions & show a screen telling the user how to update their app settings.
> 
> What did you use to check camera permissions?

_Android_:
```javascript
import { PermissionsAndroid } from 'react-native'
```

_iOS_:
```javascript
import Permissions from 'react-native-permissions'
```

**Comment by GuillaumeSarfati** [comment]
Thank you !

I has the same problem on Expo don't forget to ask for the permission and don't call the component before the return of the camera permission.

```js

import { Permissions } from 'expo';

// ...

async componentDidMount() {
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    this.setState({ hasCameraPermission: status === 'granted' });
  }
```

**Comment by Kerumen** [comment]
It appears that there are several solutions to this problem. Closing!
