### ISSUE TITLE
no result after scan on Android

### ISSUE THREAD

**Issue by Da-Lu** [Kerumen/react-native-awesome-card-io#67]
```
CardIOModule
      .scanCard({useCardIOLogo: true, requireCardholderName: true})
      .then(card => {
        // never called
      })
      .catch(() => {
        // never called
      })
```
it seems that then and catch callback never called when scan finished on Android. I can't the information about the card

**Comment by iLeafSolutionsPvtLtd** [comment]
Not Fixed

**Comment by peter-pogocarshare** [comment]
Any luck with this? It works great on ios. I've tried to log out when the "onActivityResult" method is called but it doesn't fire on Android.

My logCat is reporting
```E/SurfaceFlinger: Failed to find layer (com.pogocarshare.test/io.card.payment.DataEntryActivity#0) in layer parent (no-parent).```

I'll report back if I can figure it out.

**Comment by peter-pogocarshare** [comment]
My issue was that my MainActivity was not extending from ReactActivity. After resolving that, the lib worked great.

**Comment by otterbotter** [comment]
Did you guys manage to fix this?
I'm currently stuck on this and can't find any working solutions.

**Comment by peter-pogocarshare** [comment]
Hi there, 

In my case, the issue wasn't with this module. The issue was that this module doesn't work out-of-box with other modules which extend ReactActivity.

`MainActivity.java` should be in the form: 
```
public class MainActivity extends ReactActivity {
}
```

Check that file in case you've changed it. In my case, I changed it when installing another react-native module.

If you don't want to revert to the above, you need to revise the module to 'getCurrentActivity' in another way. This is a call back that picks up the data from the ReactActivity.

**Comment by otterbotter** [comment]
@peter-pogocarshare thanks for getting back to me Peter.

I have now created a new react native app, detached it, linked this module and deployed to my physical device.

I am still not getting any return after scanning my card.

My MainActivity.java looks like this:

```
package host.exp.exponent;

import android.os.Bundle;

import com.facebook.react.ReactPackage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import host.exp.exponent.generated.DetachBuildConstants;
import host.exp.exponent.experience.DetachActivity;

public class MainActivity extends DetachActivity {

  @Override
  public String publishedUrl() {
    return "exp://exp.host/@jaronrademeyer/cbo-demo-app";
  }

  @Override
  public String developmentUrl() {
    return DetachBuildConstants.DEVELOPMENT_URL;
  }

  @Override
  public List<String> sdkVersions() {
    return new ArrayList<>(Arrays.asList("27.0.0"));
  }

  @Override
  public List<ReactPackage> reactPackages() {
    return ((MainApplication) getApplication()).getPackages();
  }

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  @Override
  public Bundle initialProps(Bundle expBundle) {
    // Add extra initialProps here
    return expBundle;
  }
}

```

I haven't edited this file.

Not sure what's going on with my installations :-(
I did have to change the build tools from 23 to 25 (Android Studio wouldn't build otherwise), could that be it?

**Comment by peter-pogocarshare** [comment]
@otterbotter Np. 

Are you using create-react-native-app? It looks like your MainActivity is extending DetachActivity.

Try using writing your react native app by hand, or using native-base's template.

Your `MainActivity.java` should be more like this:

```
package com.pogocarshare;

import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "PogoCarshare";
    }
}
```

**Comment by otterbotter** [comment]
@peter-pogocarshare Hi peter, thanks so much for your input.

Hopefully the issue you have identified is what is causing my problem- let me try and make this change tonight and over the weekend and I'll update you on what happens.

**Comment by otterbotter** [comment]
@peter-pogocarshare I've succeeded! The issue was what you predicted: using create-react-native-app and then detaching from Expo.

Now that my MainActivity.java extends ReactActivity and not DetachActivity, the issue has been resolved.

Thanks so much peter!

**Comment by peter-pogocarshare** [comment]
🙌🙌🙌 I’m glad you perservered!

**Comment by miraan** [comment]
Is there anyway for this to work on Android with MainActivity extending DetachActivity, as I'm still using ExpoKit?

**Comment by otterbotter** [comment]
@miraan I am not sure to be honest. I'm new to the mobile development world.

You may be able to start your project without Expo, then install ExpoKit afterwards to avoid detaching?
I may be wrong though.

Good luck!

**Comment by peter-pogocarshare** [comment]
I would recommend checking with Expo and seeing if they can/do expose the event. If they are open source, then definitely put in a pull request! 

You might be able to revise this library to work with whatever Expo exposes.

**Comment by praveenp-od** [comment]
I'm still facing this issue. My Mainactivity extends ReactActivity

**Comment by ss910423** [comment]
Hi, @peter-pogocarshare. It doesn't work on my side
I used native code not expo.
Please let me know how to use this plugin, I followed the git doc.
Thanks
