### ISSUE TITLE
CardIOModule.scanCard not returning result

### ISSUE THREAD

**Issue by raju2265** [Kerumen/react-native-awesome-card-io#69]
when card scan completed it will not returning any result.please help me how can i solve this rpoblem

**Comment by ODelibalta** [comment]
Can you share some of your code? Below is mine, some sections cut out

```
CardIOModule
      .scanCard()
      .then((card) => {
        console.log(card);
      })
      .catch(() => {
        console.log('cancelled');
      });
```

**Comment by otterbotter** [comment]
I am having the same issue. Did you ever resolve this?

**Comment by Kerumen** [comment]
Is this issue still relevant? If yes, please open a new one with some code of what you are trying to achieve. Thanks!

**Comment by Njinou** [comment]
Does anyone faced the issue of keyboard entry?
The scanning works fine for me but when i enter the detail manually the done button is still not enabled
![image](https://user-images.githubusercontent.com/33528310/47813925-9f307f80-dd09-11e8-9368-69208c0c3499.png)
