### ISSUE TITLE
CardIO.h file not found

### ISSUE THREAD

**Issue by wellyal** [Kerumen/react-native-awesome-card-io#71]
I get this error when I try to build on IOS.
![image](https://user-images.githubusercontent.com/3047016/32377284-3f434906-c08e-11e7-9a79-b0df67e33dcd.png)

UPDATE1
And indeed there is no such a file on my ios dir
![image](https://user-images.githubusercontent.com/3047016/32377478-f517a92a-c08e-11e7-91cf-0f6c9ad0f4cb.png)

**Comment by m3t8d1tr** [comment]
@wellyal 
How did you solve the problem?

**Comment by Kerumen** [comment]
Version [v0.9.0](https://www.npmjs.com/package/react-native-awesome-card-io/v/0.9.0) is now released with Pod support!
