### ISSUE TITLE
cardholderName null issue

### ISSUE THREAD

**Issue by yasinugrl** [Kerumen/react-native-awesome-card-io#80]
Hello Guys,

I get the null cardholderName value  all card. Does it have any problem or this field get the specific card only?

**Comment by danielmadu** [comment]
The same problem here

**Comment by sslotsky** [comment]
I'm also getting a null `cardholderName` field. This doesn't seem like expected behavior. The name reads quite clear on the card, as clear as all the other fields which come through just fine.

**Comment by sslotsky** [comment]
My apologize, it seems I should've read the docs better!

@danielmadu @yasinugrl if you are using `CardIOModule` then the way to solve this is to call:

```javascript
    CardIOModule.scanCard({ requireCardholderName: true })
```

However if you're using `CardIOView` then I'm not sure.

**Comment by yasinugrl** [comment]
Hi @sslotsky thank for your answers.

**Comment by danielmadu** [comment]
I'm using `requireCardholderName: true` but still not work

**Comment by mobileforsh** [comment]
I can't get holder name too ;(
version: 

> "react-native-awesome-card-io": "^0.8.2",

**Comment by cinder92** [comment]
same issue here
