### ISSUE TITLE
undefined is not an object (evaluating CardIOUtilities.DETENTION_MODE)

### ISSUE THREAD

**Issue by ntk860** [Kerumen/react-native-awesome-card-io#85]
I am trying to use awesome-card-io and I am getting this error. I already did exp detach, and react-native link, it says that the library were linked successfully but its not working, I am still getting the error. Any help ?

**Comment by Kerumen** [comment]
@ntk860 Did you try to relaunch the packager?

**Comment by ntk860** [comment]
@Kerumen Yes I did. I think the problem is on NativeModule, its not being imported. 😞

**Comment by ntk860** [comment]
I am using expo

**Comment by Kerumen** [comment]
@ntk860 You can't use custom libraries with expo. You'll need to [detach](https://docs.expo.io/versions/latest/guides/detach.html).

**Comment by ntk860** [comment]
I dont understand why it was closed. I am using exp, and I already did detach, but still not working

**Comment by jeremypagley** [comment]
Not sure why this issue is closed I am getting the same issue right after installing linking and then importing it? Any idea how to fix this?

**Comment by praveenp-od** [comment]
I am also facing the same issue in IOS

**Comment by aranda-adapptor** [comment]
I got this working. I had a second build scheme and the native library was not added to the link step. In XCode, select your scheme and go to Build Phases -> Link Binary With Libraries and make sure libRNCardIO.a is in the list. Add it if it is not.
