### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by ascariandrea** [Kerumen/react-native-awesome-card-io#88]
Hi @Kerumen,
I created ts definition types for your library.
Can I submit a PR or you prefer [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by Kerumen** [comment]
Hello @ascariandrea!

Thanks for the contribution. I'm not into Typescript at all, what's the best way to integrate definitions in a project?

**Comment by ascariandrea** [comment]
I would add the `index.d.ts` to the project, and keep it in sync with package versioning.

**Comment by Kerumen** [comment]
Cool! Can you set up a PR for this? I would be happy to merge it :)

**Comment by ascariandrea** [comment]
Opened #89

**Comment by m-tymchyk** [comment]
What the real status of this issue?
I saw the PR #89, that was declined. Why?

**Comment by pqkluan** [comment]
@m-tymchyk You could try to install the Typescript package of this lib:
```bash
$ yarn add @types/react-native-awesome-card-io --dev
```

**Comment by Kerumen** [comment]
Indeed, the types have been published to [DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped)!
