### ISSUE TITLE
cardholder name -- has anyone been able to receive this on a scan?

### ISSUE THREAD

**Issue by peacechen** [Kerumen/react-native-awesome-card-io#94]
I'm using the current `react-native-awesome-card-io` 0.7.0 and have not seen the cardholder name returned on a dozen different credit cards.  I've tested on a physical iPad and Android Nexus 6.

I've set the config field `requireCardholderName` as per the documentation and as noted in #80.  Sifting through the Card.Io iOS/Android repos, there are issue threads which indicate that name scanning isn't functional.  I'm confused because this library added the `requireCardholderName` config option, and some people seem to imply that it works.

```
    CardIOModule
      .scanCard({
        hideCardIOLogo: true,
        suppressManualEntry: true,
        suppressConfirmation: true,
        requireExpiry: true,
        requireCVV: false,
        requireCardholderName: true,
      })
      .then(card => {
        //...
      })
```

**Comment by peacechen** [comment]
I have a vague recollection that the cardholder name is collected on the text input form, not automatically detected via image recognition.

**Comment by mobileforsh** [comment]
I can't get holder name too ;( I've tried with a lot of cards

**Comment by meta-jai-garg** [comment]
not able to receive card holder name on latest version

react-native: 0.60.4
react-native-awesome-card-io: 0.8.2

**Comment by Kerumen** [comment]
@peacechen is right. 

If you want the cardholder name, you have to set `suppressManualEntry` to `false` (as it's entered by the user).
