### ISSUE TITLE
No data returned after function call (Android)

### ISSUE THREAD

**Issue by otterbotter** [Kerumen/react-native-awesome-card-io#95]
Hi

I am able to call the scanCard() function, scan the card and submit the confirmation, but there is no data returned. 

My application is correctly detached and linked AFAIK.
I have tested on both a Huawei P10 Lite and Galaxy S8.

Attached is a log file of one complete interaction (click scan -> scan card -> enter CVV -> submit).

I am using:

-     "expo": "^27.0.1",
-     "react": "16.3.1",
-     "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
-     "react-native-awesome-card-io": "^0.7.0",
-     "react-navigation": "^2.3.1"

My code: 
```
import React, { Component } from 'react';
import { Picker, Platform, Text, StyleSheet, AppRegistry, View, ScrollView,
  Button, Alert, Animated, TouchableOpacity, TouchableNativeFeedback, TextInput
} from 'react-native';
import {
  createStackNavigator,
} from 'react-navigation';
import { CardIOModule, CardIOUtilities } from 'react-native-awesome-card-io';


class AlignItemsBasics extends Component {

  componentWillMount() {
     if (Platform.OS === 'ios') {
       CardIOUtilities.preload();
     }
   }

   scanCard() {
     CardIOModule
       .scanCard()
       .then(card => {
         console.log(card)

       })
       .catch(() => {
         console.log('error')
       })
   }

   render() {
     return (
       <View>
         <TouchableOpacity onPress={this.scanCard.bind(this)}>
           <Text>Scan card!</Text>
         </TouchableOpacity>
       </View>
     );
   }
```

Any help would be greatly appreciated. 
This library is core to what I'm developing and I'm quite stuck at the moment :) 

#67
#69

**Comment by otterbotter** [comment]
Resolved (see #67) with peter's suggestions.

The problem is that I was creating my react native app first with `create-react-native-app` and then detaching from Expo.

After re-creating with `react-native init ProjectName` it worked as expected.

**Comment by yvasiuk-sphere** [comment]
@otterbotter please, close issue if it has been resolved successfully

**Comment by otterbotter** [comment]
@yvasiuk-sphere Closed - thanks.
