### ISSUE TITLE
CardIOModule.scanCard() does not resolve on Android detached from Expo

### ISSUE THREAD

**Issue by miraan** [Kerumen/react-native-awesome-card-io#96]
Same as https://github.com/Kerumen/react-native-awesome-card-io/issues/67.

CardIOModule.scanCard() does not resolve on Android detached from Expo.

The issue seems to be that `MainActivity extends DetachActivity` rather than `MainActivity extends ReactActivity`.

Is there a fix?

**Comment by miraan** [comment]
A solution mentioned at https://github.com/expo/expo/issues/651 looks promising. Will give it a go and report back here.

**Comment by miraan** [comment]
Can confirm that solution mentioned in https://github.com/expo/expo/issues/651 works. Specifically for this issue:

In the react-native-awesome-card-io build.gradle, add a dependency on the exponent module:

```
implementation('host.exp.exponent:expoview:28.0.0@aar') {
    exclude module: 'CreditCardEntry'
}
```

Make `RNCardIOModule` implement `ActivityResultListener` (`host.exp.exponent.ActivityResultListener`).

In the constructor use `Exponent.getInstance().addActivityResultListener(this);` instead of `reactContext.addActivityEventListener(this);`.

Remove the first parameter `Activity activity` from the `onActivityResult` result.

```
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
```

**Comment by Kerumen** [comment]
@miraan proposed a solution, closing this issue.
