### ISSUE TITLE
Other Card

### ISSUE THREAD

**Issue by miguelalvescosta** [Kerumen/react-native-awesome-card-io#97]
Hi,
Is it possible to detect any card and take a picture?

**Comment by hmenzagh** [comment]
Any embossed card. But this is not an issue ..

**Comment by Kerumen** [comment]
This library is a wrapper around [card.io](https://www.card.io/).

It offers the same functionality of the SDK, exposed to React Native. If something is missing, feel free to open an issue on their side. Thanks!
