### ISSUE TITLE
languageOrLocale Java error Android

### ISSUE THREAD

**Issue by hmenzagh** [Kerumen/react-native-awesome-card-io#98]
Android: 7.0
RN: 0.55
Version: latest

Snippet: 

```
scanCard = () => {
		CardIOModule
			.scanCard({
				languageOrLocale: 'fr',
				guideColor: processColor(colors.prestau_red),
				useCardIOLogo: true,
			})
			.then((card) => {
				this.props.payOrder(card);
			})
			.catch(() => {
				// the user cancelled
			});
	}
```

That gives me a java error : 

![image](https://user-images.githubusercontent.com/21102398/42354422-0a06a8a6-80c7-11e8-9420-56dd0e9d0886.png)

(Thanks a lot for that repo btw)

**Comment by Kerumen** [comment]
This should be fixed in the last version. Can you try it? Thanks!
