### ISSUE TITLE
Enter manually Button Text Issue 

### ISSUE THREAD

**Issue by praveenp-od** [Kerumen/react-native-awesome-card-io#99]
Enter manually button not correctly visible in android
it shows the text 'KeyBoard'

Any updates on the Keyboard Button Text change

**Comment by praveenp-od** [comment]
and non embossed cards are not scanned

**Comment by Kerumen** [comment]
Can you try with the [last version](https://www.npmjs.com/package/react-native-awesome-card-io/v/0.9.0) of the library?
If it doesn't fix the problem, feel free to reopen the issue with a reproduction, I'll investigate!
